// <auto-generated />
using System;
using CavisteApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CavisteApp.Migrations
{
    [DbContext(typeof(CavisteDbContext))]
    [Migration("20260706101212_AjoutImageVin")]
    partial class AjoutImageVin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("CavisteApp.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdressePostale")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CavisteApp.Models.CommandeFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("TEXT");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("CommandesFournisseur");
                });

            modelBuilder.Entity("CavisteApp.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("CavisteApp.Models.LigneCommandeFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandeFournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantiteCommandee")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantiteRecue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VinId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandeFournisseurId");

                    b.HasIndex("VinId");

                    b.ToTable("LignesCommandeFournisseur");
                });

            modelBuilder.Entity("CavisteApp.Models.LigneVente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VinId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VenteId");

                    b.HasIndex("VinId");

                    b.ToTable("LignesVente");
                });

            modelBuilder.Entity("CavisteApp.Models.Vente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateVente")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Ventes");
                });

            modelBuilder.Entity("CavisteApp.Models.Vin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origine")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SeuilBas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("Vins");
                });

            modelBuilder.Entity("CavisteApp.Models.CommandeFournisseur", b =>
                {
                    b.HasOne("CavisteApp.Models.Fournisseur", "Fournisseur")
                        .WithMany("Commandes")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("CavisteApp.Models.LigneCommandeFournisseur", b =>
                {
                    b.HasOne("CavisteApp.Models.CommandeFournisseur", "CommandeFournisseur")
                        .WithMany("Lignes")
                        .HasForeignKey("CommandeFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisteApp.Models.Vin", "Vin")
                        .WithMany("LignesCommande")
                        .HasForeignKey("VinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommandeFournisseur");

                    b.Navigation("Vin");
                });

            modelBuilder.Entity("CavisteApp.Models.LigneVente", b =>
                {
                    b.HasOne("CavisteApp.Models.Vente", "Vente")
                        .WithMany("Lignes")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisteApp.Models.Vin", "Vin")
                        .WithMany("LignesVente")
                        .HasForeignKey("VinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vente");

                    b.Navigation("Vin");
                });

            modelBuilder.Entity("CavisteApp.Models.Vente", b =>
                {
                    b.HasOne("CavisteApp.Models.Client", "Client")
                        .WithMany("Ventes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CavisteApp.Models.Vin", b =>
                {
                    b.HasOne("CavisteApp.Models.Fournisseur", "Fournisseur")
                        .WithMany("Vins")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("CavisteApp.Models.Client", b =>
                {
                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("CavisteApp.Models.CommandeFournisseur", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("CavisteApp.Models.Fournisseur", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Vins");
                });

            modelBuilder.Entity("CavisteApp.Models.Vente", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("CavisteApp.Models.Vin", b =>
                {
                    b.Navigation("LignesCommande");

                    b.Navigation("LignesVente");
                });
#pragma warning restore 612, 618
        }
    }
}
